<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */

/**
 * Setup vendor autoloader
 */
if ( is_file( implode( DIRECTORY_SEPARATOR, [ dirname( __DIR__ ),'vendor', 'autoload.php'] ) ) ) {
	require_once implode( DIRECTORY_SEPARATOR, [ dirname( __DIR__ ),'vendor', 'autoload.php'] );
}

require_once implode( DIRECTORY_SEPARATOR, [ dirname( __DIR__ ), 'config', 'application.php' ] );

/**
 * Put custom settings in custom.php
 */
if ( is_file( implode( DIRECTORY_SEPARATOR, [ dirname( __DIR__ ), 'config', 'custom.php' ] ) ) ) {
	require_once implode( DIRECTORY_SEPARATOR, [ dirname( __DIR__ ), 'config', 'custom.php' ] );
}

/**
 * Bootstrap WordPress
 */
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH',  implode( DIRECTORY_SEPARATOR, [ dirname( __DIR__ ), 'public', 'wp' ] ) . DIRECTORY_SEPARATOR );
}
require_once ABSPATH . 'wp-settings.php';
